# Time in seconds
# Current in amps
# position, velocity, and acceleration in device units
my_joint_actuator:
  actuator_name: 'test_joint_actuator'
  serial_number: '0x602060002998'
  operation_mode: 'profile_velocity'
  communication_protocol: 'RS232' # or USB
  clear_faults: true

  motor:
    type: 10
    ec_motor:
      nominal_current: 2.6
      max_output_current: 9.00
      thermal_time_constant: 2.7
      number_of_pole_pairs: 1

  sensor:
    type: 1
    incremental_encoder:
      resolution: 1000
      inverted_polarity: false

  safety:
    max_following_error: 20000
    max_profile_velocity: 8000
    #max_acceleration: 12000

  #position_profile:
    #velocity: 10000
    #acceleration: 8000
    #deceleration: 3500

  velocity_profile:
    acceleration: 8000
    deceleration: 3500
